### ISSUE TITLE
No description provided.

### ISSUE THREAD

**Issue by code004Accepted** [Fedoraer/LuoguJudgeHacker#16]

**Comment by memset0** [comment]
我觉得弄不掉的。。。

还有出售尸体是不是过分了。

**Comment by code004Accepted** [comment]
> 我觉得弄不掉的。。。
> 
> 还有出售尸体是不是过分了。

个人认为此人不应该存在qwq

**Comment by memset0** [comment]
@code004Accepted 这位 ＠Fedoraer 无非就是“小学生”了点，做出的事情也没影响到你什么。等他之后自己也会明白的

**Comment by code004Accepted** [comment]
嗯哼

**Comment by code004Accepted** [comment]
> @code004Accepted 这位 ＠Fedoraer 无非就是“小学生”了点，做出的事情也没影响到你什么。等他之后自己也会明白的

没错，就这样，不过影响比较大，他搞掉了CodeVS qwq

**Comment by memset0** [comment]
@code004Accepted 搞掉 Code VS 我是真的不知道，如果是真事儿，那么的确有点过分了。。。

**Comment by code004Accepted** [comment]
@memset0 当然现在CodeVS又修了

**Comment by memset0** [comment]
@code004Accepted 哦，吓得我还去了下 Code VS （童年回忆啊

**Comment by code004Accepted** [comment]
确实搞掉了，之前luogu里讨论地热火朝天，我当时还试了，Code VS当时死了
现在好了

**Comment by memset0** [comment]
@code004Accepted 哦，那这位是有点过分

**Comment by code004Accepted** [comment]
![image](https://user-images.githubusercontent.com/36566134/46583090-cf2a9100-ca83-11e8-9342-aa69e2eb4b5e.png)
看这个，我看他是准备卡HustOJ了qwq
https://www.luogu.org/discuss/show/64941
不过是上个月的帖子了

**Comment by code004Accepted** [comment]
我去听你谷网校了啊

**Comment by memset0** [comment]
@code004Accepted QAQ，资瓷你谷

**Comment by code004Accepted** [comment]
呵呵

**Comment by VictoryDefeat** [comment]
搞事情啊

**Comment by memset0** [comment]
@VictoryDefeat  QAQ
