### ISSUE TITLE
No recommendation

### ISSUE THREAD

**Issue by Polaris1949** [Fedoraer/LuoguJudgeHacker#4]
Are you really *against* Luogu? I advise you **NOT** to do so.
By the way, taking a tour here. :stuck_out_tongue_closed_eyes:

**Comment by Polaris1949** [comment]
Test pictures for chen_zhe :stuck_out_tongue_closed_eyes:
![Picture for chen_zhe QAQ](https://raw.githubusercontent.com/Polaris1949/Disk/master/image/cz_qaq.jpg)
![Picture for chen_zhe green bird](https://raw.githubusercontent.com/Polaris1949/Disk/master/image/cz_gb.gif)

**Comment by lin-toto** [comment]
He really should have acknowledged how hard Luogu works against cheating.

**Comment by StudyingFather** [comment]
I don't think he just wants to work against Luogu...
Even I don't know what he wants to do.

**Comment by lin-toto** [comment]
Probably just want to make fun out of the online judges

**Comment by Fedoraer** [comment]
Yap I know.
So I'm now focusing on CodeVS!

**Comment by RealClearwave** [comment]
Yap,I'm stopping So Far.

**Comment by code004Accepted** [comment]
Probably he just wants to show that he is very good at making people hate him.
@lin714093880 
Qian Pai Zi Ci

**Comment by signron** [comment]
@Fedoraer However, we can't use "stop" like that.
