### ISSUE TITLE
A straightforward person does not resort to insinuations.

### ISSUE THREAD

**Issue by IGhorse** [Fedoraer/LuoguJudgeHacker#5]
# It's talk something in Chinese!

大佬啊，Orz。
不过不知道你哪来的自信1v6（甚至可能更多），你以为LG后宫组只有那几位看得见的purple？
讲实在你的嘤语真心看不懂，听LGuser说你打算10月攻克？既然这么有信心，我就提前替你把衣服买好得了，款式就按c94我最喜欢的本子的女主的来吧。
GG是罪，不是玩笑
-----------------------------
哦对了，不要放弃，保持你的决心！

**Comment by abc1763613206** [comment]
前排围观(←←)

**Comment by Lhcfl** [comment]
~~真的要It's吗。。。~~  
前排围观ing

**Comment by code004Accepted** [comment]
围观~
